- name: Basic Server Setup for Kali Linux
  hosts: all
  become: yes

  vars:
    users:
      - name: "Oleg"
        groups: "sudo"
        shell: "/bin/bash"
        password: "{{ 'OlegPassword123' | password_hash('sha512') }}"
      - name: "Ivan"
        groups: "sudo"
        shell: "/bin/bash"
        password: "{{ 'IvanPassword123' | password_hash('sha512') }}"
      - name: "Anna"
        groups: "users"
        shell: "/bin/bash"
        password: "{{ 'AnnaPassword123' | password_hash('sha512') }}"

  tasks:
    - name: Install ntpdate and synchronize time
      apt:
        name: ntpdate
        state: present

    - name: Synchronize time
      command: ntpdate pool.ntp.org

    - name: Update and upgrade the system
      apt:
        update_cache: yes
        upgrade: full

    - name: Install necessary packages
      apt:
        name:
          - vim
          - gnupg2
          - curl
          - ufw
          - unattended-upgrades
          - whois
        state: present

    - name: Add users
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        shell: "{{ item.shell }}"
        state: present
        create_home: yes
        password: "{{ item.password }}"
      loop: "{{ users }}"

    - name: Create directories for users
      file:
        path: "/home/{{ item.name }}/projects"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.groups }}"
        mode: '0755'
      loop: "{{ users }}"

    - name: Enable and start UFW firewall
      ufw:
        state: enabled
        policy: deny

    - name: Allow SSH through the firewall
      ufw:
        rule: allow
        port: 22

    - name: Allow HTTP through the firewall
      ufw:
        rule: allow
        port: 80

    - name: Allow HTTPS through the firewall
      ufw:
        rule: allow
        port: 443

    - name: Enable unattended upgrades
      copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "1";

    - name: Configure automatic security updates
      lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^//Unattended-Upgrade::Automatic-Reboot "false";'
        line: 'Unattended-Upgrade::Automatic-Reboot "true";'

    - name: Reboot the server if needed
      reboot:
        msg: "Reboot initiated by Ansible for updates."
      when: ansible_facts['os_family'] == 'Debian'


- name: Playbook to install and configure PostgreSQL 16
  hosts: all
  become: yes

  tasks:
    - name: Install ntpdate
      apt:
        name: ntpdate
        state: present

    - name: Synchronize time
      command: ntpdate pool.ntp.org

    - name: Update and upgrade the system
      apt:
        update_cache: yes
        upgrade: full

    - name: Install necessary packages
      apt:
        name:
          - vim
          - gnupg2
          - curl
        state: present

    - name: Download PostgreSQL GPG key
      get_url:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        dest: /tmp/ACCC4CF8.asc

    - name: Add PostgreSQL GPG key to the trusted list
      command: gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg /tmp/ACCC4CF8.asc
      args:
        creates: /etc/apt/trusted.gpg.d/postgresql.gpg

    - name: Add PostgreSQL repository
      command: sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
      args:
        creates: /etc/apt/sources.list.d/pgdg.list

    - name: Update the package list
      apt:
        update_cache: yes

    - name: Install PostgreSQL 16
      apt:
        name: postgresql-16
        state: present

    - name: Start and enable PostgreSQL service
      systemd:
        name: postgresql@16-main.service
        enabled: yes
        state: started
